{
 "title": "Monitoramento",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Go Routines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(echo_http_requests_total[1m])",
     "legendFormat": "{{method}} - {{handler}} - {{status}}"
    }
   ]
  },
  {
   "title": "Status Go",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{group=\"API\",job=\"go-monitoring\"}\t"
    }
   ]
  },
  {
   "title": "Cpu Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total[30s])",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Memoria Go",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{group=\"API\",job=\"go-monitoring\"}/1024/1024",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}