version: '3.0'
services:
  prometheus:
    container_name: prometheus
    restart: unless-stopped
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "bridge"
  grafana:
    container_name: grafana
    image: grafana/grafana
#    user: "admin"
#    environment:
#      - GF_SECURITY_ADMIN_USER=root
#      - GF_SECURITY_ADMIN_PASSWORD=root
#    volumes:
#      - ./grafana_db:/var/lib/grafana
    volumes:
      - ./config/grafana/:/etc/grafana/provisioning/
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini

    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    network_mode: "bridge"